
#' Calculate Simpson's Biodiversity Index (D)
#'
#' This function determines the power generated by a given flow rate for a reservoir
#' @param each_spec vector containing the number of individuals of each species
#' @param all_spec number of individuals in all species
#'
# function definition
simpson_index = function(each_spec, all_spec) {
  
  # for loop to calculate Simpson's Index
  result = 0
  Di = 0
  
  for (i in 1:length(each_spec)){
    Di = (each_spec[i]/all_spec)^2
    result = result + Di
  }
  return(result)
}
